### ISSUE TITLE
Not working on next@13.4 if src/app is not exist

### ISSUE THREAD

**Issue by numb86** [aspida/pathpida#176]
## Description

Using pathpida without `src/app` in `v13.4` of Next.js causes an error.

```
$ yarn pathpida
yarn run v1.22.19
$ /Users/numb/foo/node_modules/.bin/pathpida
node:fs:1452
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/numb/foo/src/app'
    at Object.readdirSync (node:fs:1452:3)
    at parseAppDir (/Users/numb/foo/node_modules/pathpida/dist/nextjs/parseAppDir.js:96:38)
    at createNextTemplate (/Users/numb/foo/node_modules/pathpida/dist/nextjs/createNextTemplate.js:34:41)
    at /Users/numb/foo/node_modules/pathpida/dist/buildTemplate.js:25:68
    at /Users/numb/foo/node_modules/pathpida/dist/cli.js:90:43
    at step (/Users/numb/foo/node_modules/pathpida/dist/cli.js:33:23)
    at Object.next (/Users/numb/foo/node_modules/pathpida/dist/cli.js:14:53)
    at fulfilled (/Users/numb/foo/node_modules/pathpida/dist/cli.js:5:58) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/numb/foo/src/app'
}
```

If `src/app` exists, it is not an error.

## Environment

- **Package version:**
  
  `v0.20.1`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
v18.16.0

- **npm version:**
9.5.1

**Comment by rikusen0335** [comment]
This is probably https://github.com/aspida/pathpida/pull/158 this PR causing issue
Seems like this isn't considering about pages directory?

I can confirm that next@^12 or pathpida@0.18.1 would work
